[project]
name = "blog-project"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "django>=6.0.5",
    "django-debug-toolbar>=6.3.0",
    "django-extensions>=4.1",
    "django-tinymce>=5.0.0",
    "ipython>=9.14.0",
    "pre-commit>=4.6.0",
    "python-slugify>=8.0.4",
]
