# Generated by Django 6.0.5 on 2026-06-13 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog_app", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="category",
            options={
                "ordering": ("id",),
                "verbose_name": "Категорию",
                "verbose_name_plural": "Категории",
            },
        ),
        migrations.AlterModelOptions(
            name="post",
            options={
                "ordering": ("-created_at",),
                "verbose_name": "Статью",
                "verbose_name_plural": "Статьи",
            },
        ),
        migrations.AlterField(
            model_name="post",
            name="published",
            field=models.BooleanField(
                default=False, verbose_name="Опубликовать статью"
            ),
        ),
    ]
