# Generated by Django 6.0.5 on 2026-06-13 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("feedback_app", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="feedback",
            name="subject",
            field=models.CharField(
                blank=True, max_length=150, null=True, verbose_name="Тема обращения"
            ),
        ),
    ]
