# Generated by Django 6.0.5 on 2026-06-19 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("feedback_app", "0002_feedback_subject"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="feedback",
            options={
                "ordering": ("-created_at",),
                "verbose_name": "Обратную связь",
                "verbose_name_plural": "Сообщения обратной связи",
            },
        ),
        migrations.AlterField(
            model_name="feedback",
            name="subject",
            field=models.CharField(
                choices=[
                    ("default", "Выберите тему обращения"),
                    ("tech", "Технический вопрос"),
                    ("collaboration", "Сотрудничество"),
                    ("complaint", "Жалоба"),
                    ("other", "Другое"),
                ],
                default=1,
                max_length=150,
                verbose_name="Тема обращения",
            ),
            preserve_default=False,
        ),
    ]
